Sprint1
botaevg/yandexgo pull request #3
Opened 2022-05-25 04:45 UTC by botaevg

2022-05-26 19:45 UTC, sergeysergeevru requested changes
Привет! Мне все понравилось, хороший код и структура. На улучшениях предлагаю разобраться с граничными значениями, ибо логика приложения пострадала.
PS. `nit` это придирки: можно исправлять если идея нравится. В общем совсем некритичное замечание :)

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +package handlers
ты мой кумир! Не так много людей кладут хендлеры сразу в интернал)

2022-05-26 19:45 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(":8080", r))
nit: можно порт в константу унести)

2022-05-26 19:45 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +func TestPostHandler(t *testing.T) {
нужно больше тесткейсов богу тестов. Давай граничные знания проверять. Касается всех тестов.

2022-05-26 19:45 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +				code:     201,
nit: я бы константу юзал из http пакета

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	}
chi не должен пропустить не get поэтому стоит избавиться от атавизма

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	w.WriteHeader(307)
а если у тебя урла в хранилище нет, то 307 тут не вяжется. нужно определять где-то ниже

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	w.WriteHeader(307)
А вот были бы тесты с граничными значениями то это можно было бы отловить)

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	fmt.Println(ListURL[id])
лучше использовать log.Println . В таком случае удобнее подменять на любой другой логер совместимый с log

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	w.WriteHeader(307)
И в качестве кода лучше http константу использовать: читать код проще)

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +		b[i] = letterAll[rand.Intn(len(letterAll))]
"math/rand" надо сидить через rand.Seed за один раз при запуске приложения

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +		b[i] = letterAll[rand.Intn(len(letterAll))]
https://pkg.go.dev/math/rand

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	}
думаю это тоже атавизм. chi не допустит этого

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	shortURL := shortURL()
тут такой интересный момент, твоя в твоей имплементации shortUrl могут возникать коллизиции и возможен случай, если для разных урлов сгенерируется одинаковый  shortURL и тогда мы перезатрём)

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	w.Write([]byte("http://localhost:8080/" + shortURL))
nit: базовую часть урла можно унести в константы

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	w.WriteHeader(201)
можно http.StatusCreated использовать

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +var ListURL = make(map[string]string)
на текущей итерации не критично, но есть  вообще я бы предпочел такие вещи уносить в отдельную структуру с которой мы общаемся по определенному интерфейсу. Тогда будет проще переезжать на другой тип хранения, допустим в базе какой-нибудь. Плюс тоже не самый лучший вариант создавать глобальные переменные со стораджем: лучше использовать Dependency Injection (это упрощает тестирование и можно мок тесты писать).  С другой стороны в следующих спринтах это будет очевидней, поэтому в первом не требую

2022-05-26 19:45 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	w.Header().Set("Location", ListURL[id])
да, если у тебя урла в базе нет, то куда мы редиректим?)

2022-05-27 05:39 UTC, botaevg commented on internal/handlers/handlers.go
> +	w.Header().Set("Location", ListURL[id])
попробую поставить BadRequest

2022-05-27 05:39 UTC, botaevg commented on internal/handlers/handlers.go
> +package handlers
^^ благодарю)

2022-05-27 13:14 UTC, botaevg commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(":8080", r))
+

2022-05-27 13:15 UTC, botaevg commented on cmd/shortener/main_test.go
> +				code:     201,
+

2022-05-27 13:15 UTC, botaevg commented on internal/handlers/handlers.go
> +	}
+

2022-05-27 13:17 UTC, botaevg commented on internal/handlers/handlers.go
> +	fmt.Println(ListURL[id])
+

2022-05-27 13:17 UTC, botaevg commented on internal/handlers/handlers.go
> +		b[i] = letterAll[rand.Intn(len(letterAll))]
+

2022-05-27 13:17 UTC, botaevg commented on internal/handlers/handlers.go
> +	}
+

2022-05-27 13:17 UTC, botaevg commented on internal/handlers/handlers.go
> +	shortURL := shortURL()
+

2022-05-27 13:17 UTC, botaevg commented on internal/handlers/handlers.go
> +	w.Write([]byte("http://localhost:8080/" + shortURL))
+

2022-05-27 13:17 UTC, botaevg commented on internal/handlers/handlers.go
> +	w.WriteHeader(201)
+

2022-05-27 13:19 UTC, botaevg commented on internal/handlers/handlers.go
> +var ListURL = make(map[string]string)
буду ждать следующий спринт:)

2022-05-28 12:37 UTC, sergeysergeevru requested changes
Привет! Все хорошо, но хочется избавиться от хардкода тестовых данных, давай это исправим)

2022-05-28 12:37 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +func TestRouter(t *testing.T) {
тогда уж давай уберем закомменченые атавизмы, если код больше не нужен

2022-05-28 12:37 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	}
имплементация вообще ничего не должна знать о тестах. Если надо проверить данные, которые должны уже быть в сервисе, значит мы кладем их при выполнении тестов, а не хардкодим.

2022-05-28 12:37 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +		err := errors.New("BadRequest")
таки мы могли просто строковый литерал использовать ниже, сам по себе инстанс ошибки не используется

2022-05-28 12:37 UTC, sergeysergeevru commented on internal/handlers/handlers.go
>  }
так удобнее читать код.
```suggestion
	if ListURL[id] == "" {
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte("Не найдено"))
		return
	} 
	w.Header().Set("Location", ListURL[id])
	w.WriteHeader(http.StatusTemporaryRedirect)
	w.Write([]byte(ListURL[id]))


}
```
и не помню писал ли раньше, можно еще использовать функцию http.Redirect для последних 3 строк

2022-05-28 12:37 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	rand.Seed(time.Now().UnixNano())
сидить пакет math/rand нужно только один раз за работу приложения, иначе мы потеряем равномерность распределения псевдослучайной величины.

2022-05-29 08:55 UTC, botaevg commented on cmd/shortener/main_test.go
> +func TestRouter(t *testing.T) {
+

2022-05-29 08:55 UTC, botaevg commented on internal/handlers/handlers.go
> +	}
+

2022-05-29 08:55 UTC, botaevg commented on internal/handlers/handlers.go
> +		err := errors.New("BadRequest")
+

2022-05-29 08:55 UTC, botaevg commented on internal/handlers/handlers.go
>  }
+

2022-05-29 08:56 UTC, botaevg commented on internal/handlers/handlers.go
> +	rand.Seed(time.Now().UnixNano())
+

2022-05-31 18:46 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +			fmt.Println(string(pathLast))
могу посоветовать использовать t.Log.  будет эффективнее. так проще отследить где и что вывелось. Можешь поэкспериментивать и сравнить)

2022-05-31 18:48 UTC, sergeysergeevru approved these changes
Отлично, сейчас выглядит гораздо лучше) Спасибо!)

2022-06-11 13:53 UTC, closed without merging