increment 4
botaevg/yandexgo pull request #4
Opened 2022-06-13 18:25 UTC by botaevg

2022-06-20 18:38 UTC, sergeysergeevru requested changes
Привет! Круто, что на предыдущем спринте была заложена хорошая архитектура, которая позволила без проблем добавить нужные фичи. Хочется поправить некоторые вещи из комментариев, чтобы спокойно двигаться дальше. Спасибо!

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/config/config.go
> +		fmt.Printf("%+v\n", err)
в таком случае лучше ошибку выше отдать. Не думаю что мы должны запускать приложение, если конфиг невозможно подгрузить

2022-06-20 18:38 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	flag.Parse()
я думаю парсинг флагов стоит унести под капот GetConfig иначе размазывается ответственность: вроде структуру конфига получили, но если нам еще нужны и флаги, то придется позаботиться о выполнении функции, которая вообще не связана с пакетом конфига.

2022-06-20 18:38 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +		}
лучше создать конструктор для метода, тогда можно сделать все поля приватными, чтобы не было соблазна ничего менять

2022-06-20 18:38 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +		storage = repositories.InMemoryStorage{}
тоже конструктор можно сделать

2022-06-20 18:38 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	myApp := NewApp(appConfig)
нужна ли здесь структура app не знаю. Ничего плохого нет в ней, просто все что описано в Run спокойно можно расположить здесь же. Минусов нет, но и плюсов тоже. В общем на твое усмотрение)

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +	ListURL[s] = body
мне почему-то анекдот вспомнился про снятие крестика или надевание исподнего. В общем у тебя инмемори это синглтон, а файл сторадж нет) В общем давай инкапсулируем мапу в InMemoryStorage. Могу даже предложить поиграться с двумя вариантами 
```
type InMemoryStorage {
     data map[string]string
}
/// а можно еще так
type InMemoryStorage map[string]string
```
тут как в рекламе твикс: попробуй обе и реши))

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +	return u, nil
nit: можно было так)
```suggestion
	return ListURL[id], nil
```

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +		//http.Error(w, err.Error(), http.StatusInternalServerError)
подозреваю комменты больше не нужны)

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +			break
можно обойтись без буленовых переменных:
```suggestion
			return strings.Join(strings.Split(line, ":")[1:], ":"), nil

```

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +	file.WriteString(s + ":" + body + "\n")
сигнатура метода `func (f *File) WriteString(s string) (n int, err error)` в данном случае важно ошибку проверить и вернуть выше если есть. Ведь если возникла ошибка на запись, значит мы ничего не записали.

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/middleapp/middleware.go
> +			io.WriteString(w, err.Error())
В таком случае пользователю стоит пятисотую вернуть. А так 200 ответ вернется.

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +		panic(err)
паника это вообще гиблое дело) Мы же может ответить клиенту что что-то идет не то. Даже больше, это клиент виноват, что отдал нам плохой json. https://github.com/golang/go/wiki/CodeReviewComments#dont-panic

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +		reader = r.Body
декодинг gzip просится в middleware. Как то таскать в каждый хендлера не комильфо)

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	if strURL != "" {
тут может стоило бы полностьюстью отвалидировать весь url. Мы же не сокращаем произвольный текст.

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +		}
похоже на то, что это можно вообще во время инициализации конфигурации делать, у нас же урл не поменяется в рантайме.

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +		err := h.storage.AddShort(strURL, shortURLs)
хоть и маленькая (2 строчки), но гордая бизнес логика. И она скопипащена в следующем хендлере, сейчас не так уж критично, но я бы предпочел вынести хотя бы в отдельный метод. + не помню писал на первом инкременте или нет, но могут возникнуть коллизии, так как имплементация ShortURL их отсутствие не гарантирует.

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	if strURL != "" {
я бы избавлялся от лишнего ветвления, для удобства кода, если валидация не проходит, то возвращаем ошибку пользователю, если ок то идем дальше:
```go
if strURL == "" {
    		// тебе здесь не нужно создавать инстанс ошибки err := errors.New("BadRequest"), если ты хочешь из него просто вытащить строчку. Э
		http.Error(w, "BadRequest", http.StatusBadRequest)
		return
}
// тут уже твой код 
shortURLs := shorten.ShortURL()
err := h.storage.AddShort(strURL, shortURLs)
``` 
так чуточку удобнее читать)

2022-06-20 18:38 UTC, sergeysergeevru commented on internal/app/app.go
> +package app
файл пуст и пакет похоже тоже)

2022-06-20 18:38 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +				repositories.InMemoryStorage{},
тут что-то не так с форматированием похоже

2022-06-20 18:38 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +		// TODO: Add test cases.
парочку тесткейсов добавить не мешало бы)

2022-06-20 19:31 UTC, botaevg commented on internal/config/config.go
> +		fmt.Printf("%+v\n", err)
+

2022-06-21 16:03 UTC, sergeysergeevru approved these changes
Стало интереснее! Спасибо!)

2022-06-21 16:03 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +		return
тогда стоит залогировать ошибку, иначе если будет непонятно почему программа не стартует

2022-06-21 16:03 UTC, sergeysergeevru commented on cmd/shortener/shortlist.txt
> +XVlBz:http://www.example.com
мне кажется этот файл не нужен вообще в репозитории) можно добавить в гит игнор и удалить.

2022-06-21 16:03 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +	s := shorten.ShortURL()
все таки генерацией короткой ссылки заниматься в имплементации стораджа не самый лучший вариант. Это должно быть где-то в районе расположения бизнес логики. Возможно я немного туманно объяснил. То есть получается последовательный вызов shorten.ShortURL() и AddShort можно было просто вынести в отдельный метод где у тебя хендлеры имплементированы. Либо в отдельный слой бизнес логики. В текущем варианте получается приходится в каждой имплементации стораджа прокидывать генерацию, что чуточку усложняет имплементацию. И в случае желания замены алгоритма генерации придется идти в каждую имплементацию и переписывать.

2022-06-21 16:03 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	_, err = url.ParseRequestURI(strURL)
nice!

2022-06-22 08:56 UTC, closed without merging