increment 9.1
botaevg/yandexgo pull request #5
Opened 2022-06-23 15:56 UTC by botaevg

2022-07-03 08:44 UTC, sergeysergeevru requested changes
Привет! Смотрится хорошо, вижу что пытался решить задачи лаконично. Но есть проблемы со смещением логики к репозитори, что негативно влияет на масштабируемость. Так же не имплементированы некоторые методы, что ломает полную совместимость компонентов.

2022-07-03 08:44 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +			log.Print("clien postgres fail")
не думаю что приложение будет работоспособно, если вернулась ошибка

2022-07-03 08:44 UTC, sergeysergeevru commented on cmd/shortener/main_test.go
> +			log.Print(tt.want.location)
у testing.T есть тоже возможность логировать, я бы предпочел его использовать, для консистентности вывода

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/postgre.go
> +	defer cancel()
непонятно зачем запускать отмену на завершении функции. Если defer отработал, значит отменять уже нечего

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	var u []repositories.APIOriginBatch
давай приучаться давать человекочитаемые названия переменны. Очень тяжело разбираться в коде когда одни a,b,d,c в переменных. Для маленького кусочка на 2-3 строчки или как итераторы в циклах еще норм, но когда код не укладывается в экран это становится проблемой.

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/cookies/cookie.go
> +var ListKey map[string]string
где-то используется данная переменная?

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/cookies/cookie.go
> +	log.Print("зашифрованный ид в виде строки: " + hex.EncodeToString(dst))
значение зашифрованной куки довольно сенситив информация на уровне пароля, лучше ее в логи не писать если мы в проде.

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	idUser := cookies.VerificationCookie(h.storage, r, &w)
в идеале я бы предложил унести все что касается обработки кук в middleware и передавать идентификатор пользователя через контекст реквеста. Тогда бы мы могли создавать сессию на любой реквест, а идентификатор вынимать из контекста только там где надо.

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +	AddShort(string, string, string) error
давай перейдем на единую модель передаваемую как аргумент, возможно для остальных методов аналогично. Иначе при каждом расширении хранимых полей мы так и будет ходить и менять сигнатуры методов везде.
```go
	AddShort(item model.URL) error
```

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +				ShortURL: "http://localhost:8080/" + key,
а если у нас BaseURL совершенно другой, то это уже будет некорректный ответ

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +				ShortURL: "http://localhost:8080/" + key,
вообще репозитории не должны вообще ничего знать об ответе и что происходит с точки зрения бизнес логики. Ядром приложения являются данные, сами данные описываются моделями (или entity, слова разные суть одна), вокруг уже моделей растут репозитори и бизнес логика. Так вот все что должен делать репозитори это положить данные в хранилище и изъять, перекладывать ответственность по генерации ответов и другой логике не нужно, ибо теряется разделение зон ответственности. И сложнее писать реализации под замену ибо это влечет дупликацию кода.

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +}
по сути это твои структуры для реквеста и респонса, о них репозитори не должен знать

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +}
здесь тоже должна быть имплементация. Не было сказано, что мы сохраняем батчем только когда в базу данных пишем)

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +func (f DBStorage) AddShortBatch(origins []APIOriginBatch, baseURL string, idEncrypt string) ([]APIShortBatch, error) {
вся работа с реквестом APIOriginBatch и респонсом APIShortBatch должны проиходить где-то выше, о них репозитори не должен знать. Как и о том какой домен используется. Как уже говорил, стоит перейти на работу с какой-то структурой, которая будет описывать что у нас хранится и крутится в бизнес логике, а не с точки зрения API сервера. Иначе при каждом желании изменить структуры реквестов нам прийдет лезть в дебри кода для изменений.

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +			n, _ := hex.DecodeString(nonce)
ошибки проверяем

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +	return "", errors.New("repo file")
имплементация?

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +	n, _ := hex.DecodeString(nonce)
проверка ошибок?

2022-07-03 08:44 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +}
мне кажется уже слишком много имплементаций для одного файла. Во всяком случае ориентироваться становится сложновато когда друг за другом идут имплементации для разных структур

2022-07-03 09:08 UTC, botaevg commented on cmd/shortener/main.go
> +			log.Print("clien postgres fail")
+

2022-07-03 09:08 UTC, botaevg commented on internal/cookies/cookie.go
> +var ListKey map[string]string
+

2022-07-03 09:29 UTC, botaevg commented on internal/repositories/storage.go
> +			n, _ := hex.DecodeString(nonce)
+

2022-07-03 09:29 UTC, botaevg commented on internal/repositories/storage.go
> +	n, _ := hex.DecodeString(nonce)
+

2022-07-03 09:46 UTC, botaevg commented on internal/handlers/handlers.go
> +	var u []repositories.APIOriginBatch
+

2022-07-03 09:47 UTC, botaevg commented on internal/cookies/cookie.go
> +	log.Print("зашифрованный ид в виде строки: " + hex.EncodeToString(dst))
+

2022-07-04 14:29 UTC, botaevg commented on internal/repositories/postgre.go
> +	defer cancel()
+

2022-07-04 15:05 UTC, botaevg commented on internal/repositories/storage.go
> +}
+

2022-07-04 15:05 UTC, botaevg commented on internal/repositories/storage.go
> +	return "", errors.New("repo file")
+

2022-07-04 19:00 UTC, botaevg commented on cmd/shortener/main_test.go
> +			log.Print(tt.want.location)
+

2022-07-04 19:00 UTC, botaevg commented on internal/repositories/storage.go
> +	AddShort(string, string, string) error
+

2022-07-04 20:20 UTC, botaevg commented on internal/repositories/storage.go
> +				ShortURL: "http://localhost:8080/" + key,
+

2022-07-04 20:20 UTC, botaevg commented on internal/repositories/storage.go
> +}
+

2022-07-04 20:20 UTC, botaevg commented on internal/repositories/storage.go
> +func (f DBStorage) AddShortBatch(origins []APIOriginBatch, baseURL string, idEncrypt string) ([]APIShortBatch, error) {
+

2022-07-05 20:11 UTC, sergeysergeevru approved these changes
Привет! Стало гораздо лучше, молодец! Спасибо)

2022-07-05 20:11 UTC, sergeysergeevru commented on internal/domain/model.go
> +}
из того что я вижу по сути только эта структура будет относиться к домену, и эту же структуру можно переиспользовать для `GetAllShort` метода: не вижу практической ценности  в URLForGetAll структуре, если на селекте база нам все равно будет выплевывать все хранящиеся поля. `APIOriginBatch`, `APIShortBatch` и `URLpair` касаются только респонсов и реквестов, я думаю их можно унести в хендлеры.

2022-07-05 20:11 UTC, sergeysergeevru commented on internal/repositories/storage.go
> +func (f FileStorage) AddShort(item domain.URLForAddStorage) (string, error) {
По логике мы просто сохраняем данные в базу и ничего не меняем в передаваемой структуре, мы и до вызова этого метода знали, что короткий урл можно достать из item.ShortURL, с моей точки зрения возвращаемый string излишен
```suggestion
func (f FileStorage) AddShort(item domain.URLForAddStorage) error {
```

2022-07-07 19:23 UTC, closed without merging